"""Custom-tab discovery — Developer Mode (David's ask 2026-09-01: let anyone
who downloads jarvis-app extend it with their own tabs/workflows, built by
their connected AI model using the app's existing conventions, without ever
touching a shared core file).

A custom tab is just a normal routes/*.py module named "tab_<slug>.py" that
additionally exposes a TAB_MANIFEST dict, plus (by the existing, unrelated
loadModule() convention already in static/js/app.js) a matching
static/js/views/<slug>.js. No manifest file, no plugin registry — same
"scan, don't register" spirit as services/skills_service.py's data/skills/
scan, just over routes/ module names instead of a data directory, since a
tab genuinely needs real importable Python (a router, optionally a service).

app.py calls mount_all() once at startup; every tab added after that needs
zero further app.py edits — the actual point, since app.py is a root-level
file outside REPO_CODE_DIRS (core/constants.py) and so isn't part of the
surface a connected model can edit.
"""
import importlib
import logging
import os
import shutil
from types import ModuleType

from core import settings as settings_store
from core.constants import BASE_DIR, DATA_DIR

logger = logging.getLogger(__name__)

ROUTES_DIR = os.path.join(BASE_DIR, "routes")
VIEWS_DIR = os.path.join(BASE_DIR, "static", "js", "views")
SERVICES_DIR = os.path.join(BASE_DIR, "services")
TAB_MODULE_PREFIX = "tab_"

# Where tabs the USER builds are stored (David's ask 2026-09-03). They used
# to be written into the app's own routes/services/static directories — i.e.
# inside the install folder, which an update replaces wholesale, silently
# destroying anything someone had built. Now they live with the rest of the
# user's data, so updates and reinstalls leave them alone.
#
# Shipped tabs (the premade TAB_TEMPLATES below) stay in the app directory:
# they're app code, they arrive with each build, and only the enabled/disabled
# choice is user state.
USER_TABS_DIR = os.path.join(DATA_DIR, "tabs")
USER_ROUTES_DIR = os.path.join(USER_TABS_DIR, "routes")
USER_SERVICES_DIR = os.path.join(USER_TABS_DIR, "services")
USER_VIEWS_DIR = os.path.join(USER_TABS_DIR, "views")

# Browser path the user-tab views are served from (mounted in app.py).
USER_VIEWS_URL = "/custom-views"

_paths_extended = False


def ensure_user_tab_dirs() -> None:
    """Create the user-tab directories and make Python able to import from
    them.

    The import trick, and why it's the right one: a tab is documented (and
    generated by the build-custom-tab skill) as `routes/tab_<slug>.py` plus an
    optional `services/<slug>_service.py`, importing each other by those exact
    names. Rather than rewrite that convention for user tabs — which would
    mean two conventions, and a skill that has to know which one applies —
    the existing `routes` and `services` packages get the user directories
    appended to their `__path__`. Python then resolves `routes.tab_foo` and
    `services.foo_service` from either location, so one convention covers
    both and a tab can be moved between them without editing a line.
    """
    global _paths_extended
    for directory in (USER_ROUTES_DIR, USER_SERVICES_DIR, USER_VIEWS_DIR):
        os.makedirs(directory, exist_ok=True)
    if _paths_extended:
        return
    import routes as routes_pkg
    import services as services_pkg
    for pkg, extra in ((routes_pkg, USER_ROUTES_DIR), (services_pkg, USER_SERVICES_DIR)):
        if extra not in pkg.__path__:
            pkg.__path__.append(extra)
    _paths_extended = True


def migrate_user_tabs() -> list[str]:
    """Move any user-authored tab already sitting in the app directory into
    the data directory, once.

    Needed because builds before this change wrote tabs into the install
    folder — those would be destroyed by the very next update. Template tabs
    are skipped: their files are shipped app code, not user work.
    """
    ensure_user_tab_dirs()
    templates = template_slugs()
    moved = []
    if not os.path.isdir(ROUTES_DIR):
        return moved
    for filename in sorted(os.listdir(ROUTES_DIR)):
        if not (filename.startswith(TAB_MODULE_PREFIX) and filename.endswith(".py")):
            continue
        slug = filename[len(TAB_MODULE_PREFIX):-3]
        if not slug or slug in templates:
            continue
        pairs = [
            (os.path.join(ROUTES_DIR, filename), os.path.join(USER_ROUTES_DIR, filename)),
            (os.path.join(VIEWS_DIR, f"{slug}.js"), os.path.join(USER_VIEWS_DIR, f"{slug}.js")),
            (os.path.join(SERVICES_DIR, f"{slug}_service.py"), os.path.join(USER_SERVICES_DIR, f"{slug}_service.py")),
        ]
        try:
            for src, dst in pairs:
                if os.path.exists(src) and not os.path.exists(dst):
                    shutil.move(src, dst)
                elif os.path.exists(src):
                    os.remove(src)  # already migrated; drop the install-dir copy
            moved.append(slug)
        except OSError:
            logger.exception("custom_tabs: couldn't migrate user tab '%s'", slug)
    if moved:
        logger.info("custom_tabs: migrated user tabs to the data directory: %s", ", ".join(moved))
    return moved

# Premade tabs (David's ask 2026-09-03). Their code ships with the app but
# stays dormant until a user adds one from the New Tab gallery — a fresh
# download shouldn't arrive carrying somebody else's workflow, but rebuilding
# a working tab from scratch just to try it is worse. So: shipped, not
# mounted, one click to switch on.
#
# Each entry is a real tab already built to the routes/tab_<slug>.py
# convention; enabling just makes discover() stop skipping it.
TAB_TEMPLATES = {
    "school": {
        "label": "School",
        "blurb": "Track courses, assignments and due dates, with a per-course chat that remembers what you're working on.",
        "detail": "Built around coursework: add assignments with due dates, keep drafts, and talk to JARVIS about a specific class in a chat that accumulates that course's context.",
    },
}


def template_slugs() -> set[str]:
    return set(TAB_TEMPLATES)


def enabled_templates() -> set[str]:
    return set(settings_store.get_setting("enabled_tab_templates") or [])


def list_templates() -> list[dict]:
    enabled = enabled_templates()
    return [
        {"slug": slug, "enabled": slug in enabled, **meta}
        for slug, meta in sorted(TAB_TEMPLATES.items(), key=lambda kv: kv[1]["label"])
    ]


def set_template_enabled(slug: str, enabled: bool) -> dict:
    if slug not in TAB_TEMPLATES:
        raise KeyError(slug)
    current = enabled_templates()
    if enabled:
        current.add(slug)
    else:
        current.discard(slug)
    settings_store.update_settings(enabled_tab_templates=sorted(current))
    return {"slug": slug, "enabled": enabled}


def discover() -> list[tuple[str, ModuleType]]:
    """(slug, imported module) for every discovered tab, sorted by slug.

    Scans both locations: the app's own routes/ (shipped template tabs) and
    the user's data directory (tabs they built). Both import as
    `routes.tab_<slug>` thanks to the extended package path — see
    ensure_user_tab_dirs().
    """
    ensure_user_tab_dirs()
    templates = template_slugs()
    enabled = enabled_templates()

    # slug -> is_user_tab. User tabs win on a name clash: someone's own work
    # should never be shadowed by a shipped tab that happens to match.
    candidates: dict[str, bool] = {}
    for directory, is_user in ((ROUTES_DIR, False), (USER_ROUTES_DIR, True)):
        if not os.path.isdir(directory):
            continue
        for filename in sorted(os.listdir(directory)):
            if not (filename.startswith(TAB_MODULE_PREFIX) and filename.endswith(".py")):
                continue
            slug = filename[len(TAB_MODULE_PREFIX):-3]
            if not slug:
                continue
            # A premade tab's code ships with the app but stays invisible
            # until the user adds it from the New Tab gallery.
            if not is_user and slug in templates and slug not in enabled:
                continue
            candidates[slug] = is_user

    found = []
    for slug in sorted(candidates):
        module_name = f"{TAB_MODULE_PREFIX}{slug}"
        try:
            mod = importlib.import_module(f"routes.{module_name}")
        except Exception:
            # A broken custom tab shouldn't take the whole app down — same
            # "degrade gracefully" posture as core/channels/discord_channel.py's
            # own optional-feature handling.
            logger.exception("custom_tabs: failed to import routes.%s, skipping", module_name)
            continue
        mod._jarvis_is_user_tab = candidates[slug]
        found.append((slug, mod))
    return found


def mount_all(app) -> None:
    for slug, mod in discover():
        router = getattr(mod, "router", None)
        if router is None:
            logger.warning("custom_tabs: routes.tab_%s has no `router`, skipping", slug)
            continue
        app.include_router(router)
        logger.info("custom_tabs: mounted tab_%s", slug)


def mount_one(app, slug: str) -> bool:
    """Mount a single tab's router into the already-running app, so adding a
    premade tab works immediately instead of "now restart the server."
    FastAPI accepts include_router after startup; the route table is just a
    list. Idempotent — mounting an already-mounted prefix is skipped."""
    try:
        mod = importlib.import_module(f"routes.{TAB_MODULE_PREFIX}{slug}")
    except Exception:
        logger.exception("custom_tabs: couldn't import routes.tab_%s", slug)
        return False
    router = getattr(mod, "router", None)
    if router is None:
        return False
    prefix = getattr(router, "prefix", "")
    if prefix and any(getattr(r, "path", "").startswith(prefix) for r in app.routes):
        return True  # already mounted (e.g. enabled twice in one session)
    app.include_router(router)
    app.openapi_schema = None  # force the schema to regenerate with the new routes
    logger.info("custom_tabs: mounted tab_%s at runtime", slug)
    return True


def list_manifests() -> list[dict]:
    manifests = []
    for slug, mod in discover():
        manifest = getattr(mod, "TAB_MANIFEST", None)
        if not manifest:
            continue
        # view_url tells the frontend where to import this tab's view from.
        # Shipped tabs live in the bundled static/js/views/ and keep the
        # relative import app.js has always used; user tabs are served from
        # the data directory via the /custom-views mount.
        is_user = getattr(mod, "_jarvis_is_user_tab", False)
        manifests.append({
            "id": manifest.get("id", slug),
            "label": manifest.get("label", slug),
            "icon_svg": manifest.get("icon_svg", ""),
            "view_url": f"{USER_VIEWS_URL}/{slug}.js" if is_user else None,
            "user_tab": is_user,
        })

    # Reorderable (David's ask 2026-09-01, Settings > Admin > Custom Tabs) —
    # anything not yet in the saved order (a brand new tab) falls back to
    # alphabetical (discover()'s own sort), appended after everything
    # that's already been explicitly ordered.
    order = settings_store.get_setting("custom_tab_order") or []
    order_index = {slug: i for i, slug in enumerate(order)}
    manifests.sort(key=lambda m: order_index.get(m["id"], len(order)))
    return manifests


def delete(slug: str) -> dict:
    """Removes a custom tab's convention files. No-op-safe on anything
    already missing (matches services/notes_service.py's delete_note style)
    — same shape whether called once or twice. The manifest disappears from
    list_manifests() immediately (discover() re-scans the directory fresh
    on every call, nothing cached), but if the tab registered its own API
    routes those stay reachable until a real restart — Python doesn't
    unmount an already-included FastAPI router at runtime. Same "needs a
    restart" caveat the build-custom-tab Skill already states for *adding*
    a tab, now also true for removing one."""
    # A premade tab's files are shipped app files, not something the user
    # created — deleting them would break the gallery and be undone by the
    # next update anyway. Switching it off is the correct "remove".
    if slug in TAB_TEMPLATES:
        set_template_enabled(slug, False)
        return {"removed": [], "disabled": slug}

    ensure_user_tab_dirs()
    removed = []
    # Both locations: the data directory is where user tabs live now, and the
    # app directory is checked too so a tab created by an older build (before
    # they moved) can still be deleted.
    candidates = [
        os.path.join(USER_ROUTES_DIR, f"{TAB_MODULE_PREFIX}{slug}.py"),
        os.path.join(USER_VIEWS_DIR, f"{slug}.js"),
        os.path.join(USER_SERVICES_DIR, f"{slug}_service.py"),
        os.path.join(ROUTES_DIR, f"{TAB_MODULE_PREFIX}{slug}.py"),
        os.path.join(VIEWS_DIR, f"{slug}.js"),
        os.path.join(SERVICES_DIR, f"{slug}_service.py"),
    ]
    for path in candidates:
        if os.path.exists(path):
            os.remove(path)
            removed.append(os.path.basename(path))
    return {"removed": removed}
